// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {bindings} from '../models';

export function CurrentUser():Promise<models.User>;

export function IsAuthenticated():Promise<boolean>;

export function Login(arg1:string,arg2:string):Promise<bindings.LoginResult>;

export function Logout():Promise<void>;

export function Register(arg1:string,arg2:string,arg3:string,arg4:string):Promise<bindings.LoginResult>;
