// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CurrentUser() {
  return window['go']['bindings']['AuthBinding']['CurrentUser']();
}

export function IsAuthenticated() {
  return window['go']['bindings']['AuthBinding']['IsAuthenticated']();
}

export function Login(arg1, arg2) {
  return window['go']['bindings']['AuthBinding']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['bindings']['AuthBinding']['Logout']();
}

export function Register(arg1, arg2, arg3, arg4) {
  return window['go']['bindings']['AuthBinding']['Register'](arg1, arg2, arg3, arg4);
}
