// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['bindings']['BillBinding']['Create'](arg1);
}

export function Finalize(arg1) {
  return window['go']['bindings']['BillBinding']['Finalize'](arg1);
}

export function GetByCustomerID(arg1) {
  return window['go']['bindings']['BillBinding']['GetByCustomerID'](arg1);
}

export function GetByID(arg1) {
  return window['go']['bindings']['BillBinding']['GetByID'](arg1);
}
