// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bindings} from '../models';
import {models} from '../models';

export function Create(arg1:bindings.BillInput):Promise<models.Bill>;

export function Finalize(arg1:string):Promise<void>;

export function GetByCustomerID(arg1:string):Promise<Array<models.Bill>>;

export function GetByID(arg1:string):Promise<models.Bill>;
