// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['bindings']['CustomerBinding']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['bindings']['CustomerBinding']['Delete'](arg1);
}

export function GetAll() {
  return window['go']['bindings']['CustomerBinding']['GetAll']();
}

export function GetByID(arg1) {
  return window['go']['bindings']['CustomerBinding']['GetByID'](arg1);
}

export function Update(arg1, arg2) {
  return window['go']['bindings']['CustomerBinding']['Update'](arg1, arg2);
}
