// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bindings} from '../models';
import {models} from '../models';

export function Create(arg1:bindings.CustomerInput):Promise<models.Customer>;

export function Delete(arg1:string):Promise<void>;

export function GetAll():Promise<Array<models.Customer>>;

export function GetByID(arg1:string):Promise<models.Customer>;

export function Update(arg1:string,arg2:bindings.CustomerInput):Promise<models.Customer>;
