// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bindings} from '../models';
import {models} from '../models';

export function Create(arg1:string,arg2:bindings.PaymentInput):Promise<models.Payment>;

export function GetByBillID(arg1:string):Promise<Array<models.Payment>>;
