// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1, arg2) {
  return window['go']['bindings']['PaymentBinding']['Create'](arg1, arg2);
}

export function GetByBillID(arg1) {
  return window['go']['bindings']['PaymentBinding']['GetByBillID'](arg1);
}
