// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bindings} from '../models';
import {models} from '../models';

export function Cancel(arg1:string):Promise<void>;

export function CheckIn(arg1:string):Promise<void>;

export function Checkout(arg1:string,arg2:string):Promise<void>;

export function Create(arg1:bindings.ReservationInput):Promise<models.Reservation>;

export function GetAll():Promise<Array<models.Reservation>>;

export function GetByID(arg1:string):Promise<models.Reservation>;
