// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel(arg1) {
  return window['go']['bindings']['ReservationBinding']['Cancel'](arg1);
}

export function CheckIn(arg1) {
  return window['go']['bindings']['ReservationBinding']['CheckIn'](arg1);
}

export function Checkout(arg1, arg2) {
  return window['go']['bindings']['ReservationBinding']['Checkout'](arg1, arg2);
}

export function Create(arg1) {
  return window['go']['bindings']['ReservationBinding']['Create'](arg1);
}

export function GetAll() {
  return window['go']['bindings']['ReservationBinding']['GetAll']();
}

export function GetByID(arg1) {
  return window['go']['bindings']['ReservationBinding']['GetByID'](arg1);
}
