// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateRoom(arg1) {
  return window['go']['bindings']['RoomBinding']['CreateRoom'](arg1);
}

export function CreateRoomType(arg1) {
  return window['go']['bindings']['RoomBinding']['CreateRoomType'](arg1);
}

export function GetAllRoomTypes() {
  return window['go']['bindings']['RoomBinding']['GetAllRoomTypes']();
}

export function GetAllRooms() {
  return window['go']['bindings']['RoomBinding']['GetAllRooms']();
}

export function UpdateRoom(arg1, arg2) {
  return window['go']['bindings']['RoomBinding']['UpdateRoom'](arg1, arg2);
}

export function UpdateRoomType(arg1, arg2) {
  return window['go']['bindings']['RoomBinding']['UpdateRoomType'](arg1, arg2);
}
