// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bindings} from '../models';
import {models} from '../models';

export function CreateRoom(arg1:bindings.RoomInput):Promise<models.Room>;

export function CreateRoomType(arg1:bindings.RoomTypeInput):Promise<models.RoomType>;

export function GetAllRoomTypes():Promise<Array<models.RoomType>>;

export function GetAllRooms():Promise<Array<models.Room>>;

export function UpdateRoom(arg1:string,arg2:bindings.RoomInput):Promise<models.Room>;

export function UpdateRoomType(arg1:string,arg2:bindings.RoomTypeInput):Promise<models.RoomType>;
