// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {bindings} from '../models';

export function Get():Promise<models.Settings>;

export function Save(arg1:bindings.SettingsInput):Promise<models.Settings>;
