// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {session} from '../models';
import {gorm} from '../models';

export function BuildBindings(arg1:session.Session,arg2:string):Promise<Array<any>>;

export function CloseWindow():Promise<void>;

export function DB():Promise<gorm.DB>;

export function MaximizeWindow():Promise<void>;

export function MinimizeWindow():Promise<void>;

export function ShowSaveDialog(arg1:string):Promise<string>;
