// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseWindow() {
  return window['go']['main']['App']['CloseWindow']();
}

export function MaximizeWindow() {
  return window['go']['main']['App']['MaximizeWindow']();
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function ShowSaveDialog(arg1) {
  return window['go']['main']['App']['ShowSaveDialog'](arg1);
}
